sudo: required
services:
 - docker

before_install:
 - docker build -t aneez004/docker-react -f Dockerfile.dev .

script:
 - docker run aneez004/docker-react npm run test -- --coverage

install: travis_wait mvn install

##deploy:
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "dockerreact-anees"
#  env: "DockerreactAnees-env"
#  bucket_name: "elasticbeanstalk-us-east-2-599638353756"
#  bucket_path: "dockerreact-anees"
  
#on:
# branch: master

#access_key_id: $Access_key_ID
#secret_access_key: 
#  secure: $(Secret_access_key)


